Config = {}
k_lib = {}
exports('GetLib', function() return k_lib end)

Config.HostOS = 'windows'

-- ATMs
Config.WithdrawAmounts = {
  {label = '$50'},
  {label = '$100'},
  {label = '$500'},
  {label = '$1,000'},
  {label = '$10,000'},
  {label = '$100,000'},
}

-- HACKING
Config.MaxLives = 7
Config.DefaultIpSpeed = 50
Config.DefaultTimer = {0, 20, 0}
Config.LetterRoulletteSpeeds = {{150,275}, {160,275}, {170,275}, {190,275}, {200,275}, {210,275}, {220,275}, {250,275}} --{min, max} How fast each of the 8 letters spins
Config.HackCodes = {-- must be 8 letters | LETTERS
    "FIREWALL",
    "ENCRYPTR",
    "BREACHER",
    "PHISHERX",
    "SAFELOCK",
    "HACKSAFE",
    "DEFENDER",
    "VAULTEDX",
    "SPYCODER",
    "SECUREDX",
    "INTRUDER",
    "CODEMASK",
    "BLOCKERX",
    "STEALTHY",
    "HACKSHIP",
    "GUARDIAN",
    "CYBEROPX",
    "LOCKDOWN",
    "PINCODEX",
    "SAFEKEEP",
    "HACKCASH",
    "VIGILANT",
    "THREATXX",
    "SHIELDED",
    "CODELOCK",
    "SAFEBOXX",
    "SECRETXX",
    "PHASERXX",
    "WARLOCKX",
    "DEFENSER",
    "CRIPTONX",
    "OBSCUREX",
    "SECURITY",
    "HACKWIZZ",
    "GUARDIAN",
    "BITGUARD",
    "DECODERX",
    "SHADOWXX",
    "LOCKITUP",
    "BREACHRX",
    "DIGITALX",
    "LOCKWIZZ",
    "SNEAKERX",
    "PROTECTR",
    "SECRETKX",
    "VLTCODER",
    "INTRCPTR",
    "HACKMANX",
    "GUARDEDX",
    "SAFECRYP",
    "INVISORX",
    "PHANTOMX",
    "SENSORED",
    "RESCUEED",
    "CLOAKEDX",
    "DEFEATRX",
    "SPYDROPX",
    "PASSCODX",
    "ARMOREDT",
    "XHACKERX",
    "PROTECTX",
    "ENCRYPTX",
    "LOCKHEXX",
    "SECURIXX",
    "VIRUSOXX",
    "SAFECAWX",
    "SCREWDRR",
    "PASSHIPX",
    "DEFENSXX",
    "WATCHERX",
    "PHANTAMX",
    "SECRETRR",
    "HACKBOTS",
    "XERASERX",
    "BLOCKERX",
    "CODEXPRT",
    "LOCKGENX",
    "BITDEFRL",
    "FORTIFYA",
    "SHIELDED",
    "HACKSHAD",
    "SECRETZZ",
    "EYEGUARD",
    "XCLEANER",
    "DEFENSES",
    "PASSKEEY",
    "ENCRYPTD",
    "GUARDINX",
    "RESCUXRX",
    "OBSTRUXR",
    "ELITEC0D",
    "SPYWIZRD",
    "LOCKUNLK",
    "HARDENED",
    "FORTRESS",
    "CODESAFE",
    "SAFEHAVN"
}